### ISSUE TITLE
Host Dashboard Checklist

### ISSUE THREAD

**Issue by zoton2** [esamarathon/esaw18-layouts#6]
- [x] Current donation total
- [x] Runs: last (including finish time, need to edit speedcontrol to store this, see https://github.com/speedcontrol/nodecg-speedcontrol/issues/17), coming up, after that.
- [x] Currently applicable prizes.
- [x] Upcoming goals/bidwars (need to also change server code to organise them by date/time).
- [x] Random paragraphs of information on Save the Children (check Google document), probably needs a timer too so someone doesn't start reading it out and it disappears.
